application: future-name-638
version: 1
runtime: php
api_version: 1

handlers:
# All URLs beginning with /css are treated as paths to static files in
# the css/ directory.
- url: /css
  static_dir: css
- url: /process.php
  script: process.php
- url: /conway
  script: conway.php
